# Generated by Django 4.2.10 on 2024-02-22 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='about',
            field=models.TextField(default='about'),
        ),
    ]
